services:
  backend:
    volumes:
      - ./backend:/app/backend
      - ./common:/app/common
    environment:
      - ENV=development
    command: >
      sh -c "uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"

  bot:
    volumes:
      - ./bot:/app/bot
      - ./common:/app/common
    environment:
      - ENV=development
    restart:
      unless-stopped
    command: >
      sh -c "python bot/main.py"

  frontend:
    build:
      target: dev  # Используем dev-стадию из Dockerfile
    volumes:
      - ./frontend:/app  # Монтируем исходный код для hot-reload
      - /app/node_modules  # Игнорируем node_modules внутри контейнера
    environment:
      - NODE_ENV=development
      - ENV=development
    ports:
      - "3000:3000"
    command: [ "npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000" ]
