services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"

  alembic:
    build:
      context: .
      dockerfile: backend/Dockerfile.migrations
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi_backend
    volumes:
      - uploads:/app/uploads
      - ./common:/app/common
    restart: always
    depends_on:
      - db
      - rabbitmq
      - redis  # Добавляем зависимость от Redis
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GATEWAY_TOKEN: ${GATEWAY_TOKEN}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: production
      args:
        - ENV=${ENV}
        - VITE_API_URL=${VITE_API_URL}
        - VITE_FRONTEND_HOST=${FRONTEND_HOST}
    volumes:
      - uploads:/usr/share/nginx/html/uploads
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL}
      - VITE_FRONTEND_HOST=${FRONTEND_HOST}
    ports:
      - "80:80"
    depends_on:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}  # Можно настроить через .env
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}  # По умолчанию, лучше изменить в продакшене
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: telegram_bot
    depends_on:
      - backend
      - rabbitmq
      - redis
    env_file:
      - .env
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - uploads:/app/uploads
      - ./common:/app/common

  redis:
    image: redis:6
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}

volumes:
  postgres_data:
  rabbitmq_data:
  uploads:
  redis_data:
