services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"

  alembic:
    build:
      context: .
      dockerfile: backend/Dockerfile.migrations
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: telegram_bot
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      BOT_TOKEN: ${BOT_TOKEN}
      CHANNEL_ID: ${CHANNEL_ID}
      JWT_TOKEN: ${JWT_TOKEN}
      CUSTOMER_CODE: ${CUSTOMER_CODE}
      MERCHANT_ID: ${MERCHANT_ID}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Исключаем node_modules, чтобы избежать проблем с зависимостями
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: [ "npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000" ]
    depends_on:
      - backend


  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./frontend:/app
    ports:
      - "80:80"
    depends_on:
      - backend



volumes:
  postgres_data:
