"""added tournament type column

Revision ID: 051c9da13ee4
Revises: fcac3e96feb1
Create Date: 2025-02-16 11:28:11.719580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '051c9da13ee4'
down_revision: Union[str, None] = 'fcac3e96feb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('users', 'organizer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'organizer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('tournaments', 'type')
    # ### end Alembic commands ###
