"""solid

Revision ID: 05d6699fde25
Revises: 9563c829b5be
Create Date: 2025-02-07 18:49:05.139063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d6699fde25'
down_revision: Union[str, None] = '9563c829b5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_region_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'region_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_region_id_fkey', 'users', 'regions', ['region_id'], ['id'])
    # ### end Alembic commands ###
