"""added rows in user model"


Revision ID: 08cd6ea13e84
Revises: c3563d7a8890
Create Date: 2025-03-15 10:55:03.130877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '08cd6ea13e84'
down_revision: Union[str, None] = 'c3563d7a8890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'sex')
    # ### end Alembic commands ###
