"""del sex str added sex_id

Revision ID: 0d27d2c4b609
Revises: a0193fd42ea3
Create Date: 2025-03-21 20:55:45.379037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d27d2c4b609'
down_revision: Union[str, None] = 'a0193fd42ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'sex', ['sex_id'], ['id'])
    op.drop_column('users', 'sex')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'sex_id')
    # ### end Alembic commands ###
