"""edited datetime and added time row in tournament model

Revision ID: 1087ae67b919
Revises: 08cd6ea13e84
Create Date: 2025-03-15 16:18:58.298227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1087ae67b919'
down_revision: Union[str, None] = '08cd6ea13e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('tournaments', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('tournaments', 'time')
    # ### end Alembic commands ###
