"""migrations

Revision ID: 2364a24658a2
Revises: 36f436dfbaf0
Create Date: 2025-01-10 21:50:05.962023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2364a24658a2'
down_revision: Union[str, None] = '36f436dfbaf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments_duo', sa.Column('organizer_requisites', sa.String(), nullable=True))
    op.add_column('tournaments_duo', sa.Column('organizer_contacts', sa.String(), nullable=True))
    op.add_column('tournaments_solo', sa.Column('organizer_requisites', sa.String(), nullable=True))
    op.add_column('tournaments_solo', sa.Column('organizer_contacts', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments_solo', 'organizer_contacts')
    op.drop_column('tournaments_solo', 'organizer_requisites')
    op.drop_column('tournaments_duo', 'organizer_contacts')
    op.drop_column('tournaments_duo', 'organizer_requisites')
    # ### end Alembic commands ###
