"""migrations

Revision ID: 248d40108e72
Revises: 57fa8eccad0c
Create Date: 2025-01-13 20:37:20.243769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248d40108e72'
down_revision: Union[str, None] = '57fa8eccad0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('from_who', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'from_who')
    # ### end Alembic commands ###
