"""migrations

Revision ID: 2fc55d4034a8
Revises: d2e204fbfe21
Create Date: 2025-01-12 14:03:05.390259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc55d4034a8'
down_revision: Union[str, None] = 'd2e204fbfe21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solo_tournament_members', sa.Column('fio', sa.String(), nullable=True))
    op.add_column('users_pairs', sa.Column('user1_fio', sa.String(), nullable=True))
    op.add_column('users_pairs', sa.Column('user2_fio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_pairs', 'user2_fio')
    op.drop_column('users_pairs', 'user1_fio')
    op.drop_column('solo_tournament_members', 'fio')
    # ### end Alembic commands ###
