"""sa_relationship in participant

Revision ID: 32fa2c6d804d
Revises: 929567afcbc2
Create Date: 2025-02-15 17:46:12.200039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32fa2c6d804d'
down_revision: Union[str, None] = '929567afcbc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_pairs')
    op.drop_table('solo_tournament_members')
    op.drop_table('tournaments_duo')
    op.drop_table('transactions')
    op.drop_table('tournaments_solo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solo_tournament_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('fio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments_solo.id'], name='solo_tournament_members_tournament_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='solo_tournament_members_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='solo_tournament_members_pkey')
    )
    op.create_table('tournaments_solo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('photo_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('organizer_name_and_contacts', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('organizer_requisites', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('organizer_telegram_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('can_register', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prize_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sex_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='tournaments_solo_category_id_fkey'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='tournaments_solo_region_id_fkey'),
    sa.ForeignKeyConstraint(['sex_id'], ['sex.id'], name='tournaments_solo_sex_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tournaments_solo_pkey')
    )
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('operation_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('months', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='transactions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='transactions_pkey')
    )
    op.create_table('tournaments_duo',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tournaments_duo_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('photo_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organizer_name_and_contacts', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('organizer_requisites', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('organizer_telegram_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('can_register', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prize_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sex_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='tournaments_duo_category_id_fkey'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='tournaments_duo_region_id_fkey'),
    sa.ForeignKeyConstraint(['sex_id'], ['sex.id'], name='tournaments_duo_sex_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tournaments_duo_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users_pairs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user1_fio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user2_fio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tournament_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments_duo.id'], name='users_pairs_tournament_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_pairs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pairs_pkey')
    )
    # ### end Alembic commands ###
