"""migrations

Revision ID: 3361939e44f1
Revises: 965b4402208f
Create Date: 2025-01-14 10:38:01.281963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3361939e44f1'
down_revision: Union[str, None] = '965b4402208f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainers', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('trainers', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainers', 'address')
    op.drop_column('trainers', 'phone')
    # ### end Alembic commands ###
