"""added cascade news comments

Revision ID: 3692b1f33db0
Revises: eed880a02feb
Create Date: 2025-03-23 13:10:08.871327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3692b1f33db0'
down_revision: Union[str, None] = 'eed880a02feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_creator_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('news_creator_id_fkey', 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key('news_creator_id_fkey', 'news', 'users', ['creator_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_creator_id_fkey', 'comments', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###
