"""migrations

Revision ID: 36f436dfbaf0
Revises: 0c837aa0bd19
Create Date: 2025-01-10 20:28:24.240688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f436dfbaf0'
down_revision: Union[str, None] = '0c837aa0bd19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments_duo', sa.Column('organizer_name', sa.String(), nullable=False))
    op.add_column('tournaments_solo', sa.Column('organizer_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments_solo', 'organizer_name')
    op.drop_column('tournaments_duo', 'organizer_name')
    # ### end Alembic commands ###
