"""added group tables

Revision ID: 44bac4e88b2d
Revises: 083382e2d2e9
Create Date: 2025-10-11 08:50:44.818802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '44bac4e88b2d'
down_revision: Union[str, None] = '083382e2d2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_stage',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_matches',
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('score1', sa.Integer(), nullable=True),
    sa.Column('score2', sa.Integer(), nullable=True),
    sa.Column('played', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('participant1_id', sa.Integer(), nullable=False),
    sa.Column('participant2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_stage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant1_id'], ['tournament_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant2_id'], ['tournament_participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_participants',
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_stage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['tournament_participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_participants')
    op.drop_table('group_matches')
    op.drop_table('group_stage')
    # ### end Alembic commands ###
