"""migrations

Revision ID: 57fa8eccad0c
Revises: 83c8686a1698
Create Date: 2025-01-13 19:17:52.261584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57fa8eccad0c'
down_revision: Union[str, None] = '83c8686a1698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments_duo', sa.Column('organizer_name_and_contacts', sa.String(), nullable=True))
    op.drop_column('tournaments_duo', 'organizer_contacts')
    op.drop_column('tournaments_duo', 'organizer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments_duo', sa.Column('organizer_name', sa.VARCHAR(), nullable=False))
    op.add_column('tournaments_duo', sa.Column('organizer_contacts', sa.VARCHAR(), nullable=True))
    op.drop_column('tournaments_duo', 'organizer_name_and_contacts')
    # ### end Alembic commands ###
