"""deleted time and added desc row in tournament model

Revision ID: 5958d3eda25b
Revises: 1087ae67b919
Create Date: 2025-03-15 17:17:10.507770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5958d3eda25b'
down_revision: Union[str, None] = '1087ae67b919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('desctiption', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('tournaments', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'desctiption')
    # ### end Alembic commands ###
