"""added news photo

Revision ID: 61b0cf8f0572
Revises: 7abbb5c03adc
Create Date: 2025-03-09 20:23:52.864229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '61b0cf8f0572'
down_revision: Union[str, None] = '7abbb5c03adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsphoto',
    sa.Column('photo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('news', 'photo')
    op.add_column('tournaments', sa.Column('photo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('tournaments', 'photo')
    op.add_column('trainers', sa.Column('photo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('trainers', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainers', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('trainers', 'photo_path')
    op.add_column('tournaments', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tournaments', 'photo_path')
    op.add_column('news', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('newsphoto')
    # ### end Alembic commands ###
