"""added copmleted flag in transation base model

Revision ID: 7abbb5c03adc
Revises: 09afbf3683fd
Create Date: 2025-03-09 16:43:35.980707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7abbb5c03adc'
down_revision: Union[str, None] = '09afbf3683fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'completed')
    # ### end Alembic commands ###
