"""added comment, prize_fund->str

Revision ID: 854b46d4103a
Revises: 3f022e8e9136
Create Date: 2025-03-23 17:18:23.770909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '854b46d4103a'
down_revision: Union[str, None] = '3f022e8e9136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('tournaments', 'prize_fund',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'prize_fund',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('tournaments', 'comment')
    # ### end Alembic commands ###
