"""migrations

Revision ID: 965b4402208f
Revises: 78ce8f10b6e3
Create Date: 2025-01-14 10:37:26.377055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965b4402208f'
down_revision: Union[str, None] = '78ce8f10b6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments_duo', sa.Column('address', sa.String(), nullable=True))
    op.add_column('tournaments_solo', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments_solo', 'address')
    op.drop_column('tournaments_duo', 'address')
    # ### end Alembic commands ###
