"""added region to user model

Revision ID: a0193fd42ea3
Revises: 02d8ce5fd8e4
Create Date: 2025-03-18 14:11:27.884706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0193fd42ea3'
down_revision: Union[str, None] = '02d8ce5fd8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('region_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'regions', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'region_id')
    # ### end Alembic commands ###
