"""cascade_user

Revision ID: a3c6aac4b039
Revises: b3c601da5097
Create Date: 2026-01-03 16:36:26.657290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c6aac4b039'
down_revision: Union[str, None] = 'b3c601da5097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tournament_participants_partner_id_fkey', 'tournament_participants', type_='foreignkey')
    op.drop_constraint('tournament_participants_user_id_fkey', 'tournament_participants', type_='foreignkey')
    op.create_foreign_key(None, 'tournament_participants', 'users', ['partner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tournament_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament_participants', type_='foreignkey')
    op.drop_constraint(None, 'tournament_participants', type_='foreignkey')
    op.create_foreign_key('tournament_participants_user_id_fkey', 'tournament_participants', 'users', ['user_id'], ['id'])
    op.create_foreign_key('tournament_participants_partner_id_fkey', 'tournament_participants', 'users', ['partner_id'], ['id'])
    # ### end Alembic commands ###
