"""ondelete=cascade

Revision ID: a61a3f176f15
Revises: 61b0cf8f0572
Create Date: 2025-03-10 03:31:51.202582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61a3f176f15'
down_revision: Union[str, None] = '61b0cf8f0572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_news_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'news', ['news_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('newsphoto_news_id_fkey', 'newsphoto', type_='foreignkey')
    op.create_foreign_key(None, 'newsphoto', 'news', ['news_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'newsphoto', type_='foreignkey')
    op.create_foreign_key('newsphoto_news_id_fkey', 'newsphoto', 'news', ['news_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_news_id_fkey', 'comments', 'news', ['news_id'], ['id'])
    # ### end Alembic commands ###
