"""added tournament owner

Revision ID: a61de9b54fcf
Revises: 051c9da13ee4
Create Date: 2025-02-16 11:33:34.273021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61de9b54fcf'
down_revision: Union[str, None] = '051c9da13ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tournaments', 'users', ['owner_id'], ['id'])
    op.alter_column('users', 'organizer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'organizer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_column('tournaments', 'owner_id')
    # ### end Alembic commands ###
