"""brackets

Revision ID: b3c601da5097
Revises: f898c20c9fb7
Create Date: 2026-01-01 15:31:41.633559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c601da5097'
down_revision: Union[str, None] = 'f898c20c9fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playoff_stages',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playoff_brackets',
    sa.Column('type', sa.Enum('MAIN', 'ADDITIONAL', name='brackettype'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['playoff_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playoff_rounds',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bracket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bracket_id'], ['playoff_brackets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playoff_matches',
    sa.Column('score1', sa.Integer(), nullable=True),
    sa.Column('score2', sa.Integer(), nullable=True),
    sa.Column('played', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('participant1_id', sa.Integer(), nullable=True),
    sa.Column('participant2_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant1_id'], ['tournament_participants.id'], ),
    sa.ForeignKeyConstraint(['participant2_id'], ['tournament_participants.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['playoff_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['tournament_participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playoff_matches')
    op.drop_table('playoff_rounds')
    op.drop_table('playoff_brackets')
    op.drop_table('playoff_stages')
    # ### end Alembic commands ###
