"""is_grand

Revision ID: c2f5ba8dac86
Revises: a3c6aac4b039
Create Date: 2026-01-04 10:53:50.484445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f5ba8dac86'
down_revision: Union[str, None] = 'a3c6aac4b039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('is_grand', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'is_grand')
    # ### end Alembic commands ###
