"""added cascade deletions on groupstage

Revision ID: f898c20c9fb7
Revises: 44bac4e88b2d
Create Date: 2025-10-24 18:27:50.339640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f898c20c9fb7'
down_revision: Union[str, None] = '44bac4e88b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
