"""migrations

Revision ID: 1817ed2696e1
Revises: 3361939e44f1
Create Date: 2025-01-14 15:01:43.405186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1817ed2696e1'
down_revision: Union[str, None] = '3361939e44f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments_duo', sa.Column('prize_fund', sa.Integer(), nullable=True))
    op.add_column('tournaments_solo', sa.Column('prize_fund', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments_solo', 'prize_fund')
    op.drop_column('tournaments_duo', 'prize_fund')
    # ### end Alembic commands ###
