"""migrations

Revision ID: 406d24c0fb3e
Revises: aba59f36968e
Create Date: 2025-01-16 13:49:18.338423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406d24c0fb3e'
down_revision: Union[str, None] = 'aba59f36968e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('shortname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'shortname')
    # ### end Alembic commands ###
