"""migrations

Revision ID: 5b32c824d006
Revises: 93f7e61be917
Create Date: 2025-01-13 21:55:03.684111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b32c824d006'
down_revision: Union[str, None] = '93f7e61be917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_pairs', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_pairs', 'confirmed')
    # ### end Alembic commands ###
