"""migrations

Revision ID: 78ce8f10b6e3
Revises: e8c59f5f51e6
Create Date: 2025-01-14 09:13:51.146386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ce8f10b6e3'
down_revision: Union[str, None] = 'e8c59f5f51e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duo_tournament_members')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duo_tournament_members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_pair_id', sa.INTEGER(), nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), nullable=False),
    sa.Column('confirmed', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments_duo.id'], ),
    sa.ForeignKeyConstraint(['user_pair_id'], ['users_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
