"""migrations

Revision ID: 7ec862757c7d
Revises: 8fce4fb6954d
Create Date: 2025-01-12 16:41:16.514371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec862757c7d'
down_revision: Union[str, None] = '8fce4fb6954d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('end_of_subscription', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'start_time')
    op.drop_column('users', 'end_of_subscription')
    # ### end Alembic commands ###
