"""migrations

Revision ID: 8fce4fb6954d
Revises: 2fc55d4034a8
Create Date: 2025-01-12 16:20:58.815845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fce4fb6954d'
down_revision: Union[str, None] = '2fc55d4034a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_organizer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_organizer')
    # ### end Alembic commands ###
