"""migrations

Revision ID: d2e204fbfe21
Revises: 2364a24658a2
Create Date: 2025-01-12 12:59:42.500199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e204fbfe21'
down_revision: Union[str, None] = '2364a24658a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments_duo', sa.Column('photo_id', sa.String(), nullable=True))
    op.add_column('tournaments_duo', sa.Column('organizer_telegram_id', sa.Integer(), nullable=True))
    op.add_column('tournaments_solo', sa.Column('photo_id', sa.String(), nullable=True))
    op.add_column('tournaments_solo', sa.Column('organizer_telegram_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments_solo', 'organizer_telegram_id')
    op.drop_column('tournaments_solo', 'photo_id')
    op.drop_column('tournaments_duo', 'organizer_telegram_id')
    op.drop_column('tournaments_duo', 'photo_id')
    # ### end Alembic commands ###
